trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '26.x'
  displayName: 'Install Node.js 26'

- script: |
    echo "Node version:"
    node --version

    echo "npm version:"
    npm --version

    npm install
    npm run build
  displayName: 'npm install and build'
